chat/urls.py
urlpatterns = [
    url(r'^login/$', views.Login, name='login'),
    url(r'^logout/$', views.Logout, name='logout'),
    url(r'^home/$', views.Home, name='home'),

    url(r'^post/$', views.Post, name='post')
    url(r'^messages/$', views.Messages, name='messages')

]

music/urls.py
from django.conf.urls import patterns, url
from . import views

app_name = 'music'

urlpatterns = [



    # /music/
    url(r'^$', views.IndexView.as_view(), name = 'index'),

    # /register/
    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    # /music/<album_id>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # music/album/add
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),

    # /music/album/2/
    url(r'^album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),

    # /music/album/2/delete
    url(r'^album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),

    # /music/email
    url(r'^email/$',views.EmailFormView.as_view(), name='emailSend'),

]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    url(r'^admin/', include(admin.site.urls)),
    url(r'^music/', include('music.urls', namespace='music')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=250)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + ' - ' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

'''
class User(AbstractUser):
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
'''

class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)

    # The additional attributes we wish to include.
    encrypt = models.CharField(max_length=60)


    # Override the __unicode__() method to return out something meaningful!
    def __str__(self):
        return self.encrypt.__str__

music/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import UserProfile
from website.settings import PASSWORD_HASHERS

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'PASSOWRD...','title': 'Sh...'}))
    username = forms.CharField(label='username', widget=forms.TextInput(attrs={'placeholder': 'USER NAME', 'title': 'User Name'}))
    email = forms.EmailField(required=True,widget=forms.TextInput(attrs={'placeholder': 'YOUR EMAIL...', 'title': 'xxx@mailService.yyyy'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class UserProfileForm(forms.ModelForm):
    prefixEncrypt = 'django.contrib.auth.hashers.'


    CHOICES = (
        ((PASSWORD_HASHERS[0][len(prefixEncrypt):]).strip(), 'PBKDF2'),
        ((PASSWORD_HASHERS[1][len(prefixEncrypt):]).strip(), 'PBK2SHA1'),
        ((PASSWORD_HASHERS[2][len(prefixEncrypt):]).strip(), 'SHA1'),
        ((PASSWORD_HASHERS[3][len(prefixEncrypt):]).strip(), 'MD5'),
)

    encrypt = forms.ChoiceField(choices=CHOICES)
    class Meta:
        model = UserProfile
        fields = ('encrypt', )



class EmailForm(forms.Form):

    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

music/views.py
from django.views import generic
from .models import Album, UserProfile
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserForm, UserProfileForm, EmailForm
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from website import settings

'''
class EMAILView(EmailMessage):
    def sendIt(self):
        template_name = 'music/email.html'
        to = ['pishtan231@gmail.com']
        from_email = 'pishtan231@gmail.com'
        subject = 'Automation_EMAIL'
        context = {'aaa' : 'This is the automation EMAIL with your details'}
        return self.send()
'''

class EmailFormView(View):
    form_class = EmailForm
    template_name = 'music/email.html'

    # display blank form
    def get(self, request):
        emailform = self.form_class(None)
        return render(request, self.template_name, {'data': {'emailform': emailform }})

    def post(self, requset):
        emailform = self.form_class(requset.POST)

        if emailform.is_valid():

            subject = emailform.cleaned_data['subject']
            message = emailform.cleaned_data['message']
            sender = emailform.cleaned_data['sender']
            cc_myself = emailform.cleaned_data['cc_myself']

            recipients = ['pishtan231@gmail.com']

            if cc_myself:
                recipients.append(sender)

            send_mail(subject, message, sender, recipients)
            return HttpResponseRedirect('/music/')
        else:
            return HttpResponseRedirect('/music/email/')
    '''
            # Returns User objects if credentials are correct
            user = authenticate(username=username, password=password)
            if user is not None:

                if user.is_active:
                    login(requset, user)
                    return redirect('music:index')
        return render(requset, self.template_name, {'form': form})
'''

class IndexView(generic.ListView, EmailFormView):
    template_name = 'music/index.html'
    email_template_name = 'music/email.html'
    context_object_name = 'data'
    form_class = EmailForm

    def get_queryset(self):
        emailform = self.form_class(None)
        return {
            'all_albums': Album.objects.all(),
            'emailform': emailform
        }



class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

class UserFormView(View):
    form_class = UserForm
    profile_form = UserProfileForm
    template_name = 'music/registration_form.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        formTwo = self.profile_form(None)

        return render (request, self.template_name, {'form': form, 'formTwo': formTwo})


    def post(self, requset):
        form = self.form_class(requset.POST)
        formTwo = self.profile_form(requset.POST)

        if (form.is_valid() and formTwo.is_valid()):



            # cleaned (normalized) data


            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            encrypt = formTwo.cleaned_data['encrypt']

            user = form.save(commit=False)

            user_extend = formTwo.save(commit=False)
            #indexOfMethod = settings.PASSWORD_HASHERS.index('django.contrib.auth.hashers.{}'.format(user_extend.encrypt))
            #tempMethod = settings.PASSWORD_HASHERS[0]
            if user_extend.encrypt == 'MD5PasswordHasher':
                settings.PASSWORD_HASHERS[0] = 'django.contrib.auth.hashers.MD5PasswordHasher'
             #   settings.PASSWORD_HASHERS[indexOfMethod] =  tempMethod
            if user_extend.encrypt == 'PBKDF2PasswordHasher':
                settings.PASSWORD_HASHERS[0] = 'django.contrib.auth.hashers.PBKDF2PasswordHasher'
              #  settings.PASSWORD_HASHERS[indexOfMethod] = tempMethod
            if user_extend.encrypt == 'SHA1PasswordHasher':
                settings.PASSWORD_HASHERS[0] = 'django.contrib.auth.hashers.SHA1PasswordHasher'
               # settings.PASSWORD_HASHERS[indexOfMethod] = tempMethod


            user.set_password(password)
            user.save()

            user_extend.user = user
            user_extend.save()

            # Returns User objects if credentials are correct
            user = authenticate(username=username, password=password)


            if user is not None:

                if user.is_active:
                    login(requset, user)
                    return redirect('music:index')
        return render(requset, self.template_name, {'form': form, 'formTwo': formTwo})
        '''
        def get_context_data(self, **kwargs):
            context = super(UserFormView, self).get_context_data(**kwargs)
            context['encrypt'] = 'hi1223344'
            return context
        '''

music/templates/music/album_form.html
{% extends 'music/base.html' %}

{% block body %}
<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'music/form-template.html' %}
    <div class="form-group">
        <div class="col-sm-offset-5 col-sm-3">
            <button type="submit" class="btn-success btn btn-primary pull-middle">Submit</button>
        </div>
    </div>
</form>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Viberr {% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Tangerine">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="http://www.clubdesign.at/floatlabels.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'music:index' %}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                            Albums
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'music:index' %}">
                            <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
                            Songs
                        </a>
                    </li>
                    <li class="">
                         <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button>
                            {% include 'music/email.html' %}
                    </li>
                    <li class="">
                        <a href="{% url 'music:emailSend' %}" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&nbsp;
                            SEND US E-MAIL
                        </a>
                    </li>
                </ul>

                <form class="navbar-form navbar-left" role="search" method="get" actiob="#">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>

                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'music:album-add' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                            Add Album
                        </a>
                    </li>
                                    <li class="">
                        <a href="{% url 'music:index' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                            Logout
                        </a>
                    </li>
                </ul>

            </div>

        </div>
    </nav>

{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album Details{% endblock %}
{% block body %}
    <img src="{{ album.album_logo.url }}">

    <h1>{{ album.album_title }}</h1>
    <h2>{{ album.artist }}</h2>

    {% for song in album.song_set.all %}
        {{ song.song_title }}
        {% if song.is_favorite %}
            <img src="https://cdn4.iconfinder.com/data/icons/pretty_office_3/128/Star-Full.png">
        {% endif %}
         <br>
    {% endfor %}

{% endblock %}

music/templates/music/email.html
<!-- Modal -->

  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">SEND US MAIL</h4>
        </div>
        <div class="modal-body">
          <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
              {% for field in data.emailform %}
              {% csrf_token %}
                <label class="control-label col-sm-2">{{ field.label_tag }}</label>
                    <div class="col-sm-15">{{ field }}<br><br></div>
              {% endfor %}
              <div class="form-group">
                  <div class="col-sm-offset-2 col-sm-10">
                      <button type="submit" class="btn-success">Submit</button>
                  </div>
              </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>


music/templates/music/form-template.html
<div class="container">
	<div class="row centered-form">
        <div class="col-xs-10 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
        	<div class="panel panel-default">
        		<div class="panel-heading">
					<h3 class="panel-title">Please Register   <small>Put alot of attention!</small></h3>
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-xs-10 col-sm-11 col-md-11">
							<div class="form-group">
								{% for field in form %}
								<div>{{ field.label_tag }}   {{ field }}</div><br>
								{% endfor %}

								{% for field in formTwo %}
								<div class="form-group">
									<div class="form-control input-sm floatlabel">{{ field.label_tag }}</div>
									<div>{{ field }}</div>
								{% endfor %}
								</div>

							</div>
						</div>
			    	</div>
	    		</div>
    		</div>
    	</div>
	</div>
</div>

music/templates/music/index.html
{% extends 'music/base.html' %}
index view
{% block body %}

    {% if data.all_albums %}
        <h3>Here are all my albums: index view</h3>

        <ul>
            {% for album in data.all_albums %}
                <!-- Album logo -->
                <li>
                <a href="{% url 'music:detail' album.id %}">
                    <img src="{{ album.album_logo.url }}" class="img-responsive">
                </a>
                <a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a>
                <form action="{% url 'music:album-delete' album.id %}" method="post" style="display:inline ;">
                    {% csrf_token %}
                    <input type="hidden" name="album_id" value="{{ album.id }}">
                    <button type="submit" class="btn btn-default btn-sm" name="delID{{ album.id }}">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                </form>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <h3>You don't have any albums</h3>
    {% endif %}
{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %} Register {% endblock %}
{% block body %}
<h3>Create New Account</h3>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'music/form-template.html' %}
    <div class="form-group">
    <button type="submit" class="btn-success btn btn-primary pull-middle">Submit</button>
    </div>
</form>
{% endblock %}